### ISSUE TITLE
As a user, I want to be able to use UniPath.io without having an account.

### ISSUE THREAD

**Issue by Gurpranked** [UMLCloudComputing/UniPath.io#37]
## User Story: Account-less operation

**Description:**
As a new user, I want to be able to use UniPath.io without an account to view classes and their criteria. 

### Acceptance Criteria:
- [ ] The Dashboard should show information only about the recently viewed classes. 
- [ ] The ability to view all possible classes and their criteria
- [ ] The ability to filter all possible classes via the class search section
- [ ] The ability to use schedule builder to build a schedule specific to session (temporarily)

### Tasks:
- [ ] Integrate a feature flag system for enabling or disabling features based on account type (Null account for no account)
- [ ] Integrate a default widget UI for features that require an account
- [ ] Add redirection to the account creation portal for features that need an account
- [ ] Integrate a persistent Login and Signup button at the top right of UniPath.io for when the user wants to create an account or login with their account
- [ ] Maintain a default account-less settings configuration to use: Light-mode, Dashboard layout, UniPath.io features (enabled/disabled)

### Requires:
- [ ] AWS Cognito integration
- [ ] Front End null-account UI
- [ ] Account Object creation 

Temporary Account creation
Store session data to client device?
