### ISSUE TITLE
As a user I want to be able to share my past, current, or future schedule and degree plans with other users.

### ISSUE THREAD

**Issue by Gurpranked** [UMLCloudComputing/UniPath.io#55]
### User Story 3: Schedule and degree plan sharing with other users

**Description:**
As a user, I want to share my created schedules and degree plans with other users 

### Acceptance criteria:
- [ ] The "Shared with Me" section is accessible from the persistent menu bar on the left side of the UI
- [ ] The "Shared with Me" section lists all shared schedules with information about the user they belong to, date and time of the schedule's recency, and a title of the schedule itself named by the owner.
- [ ] Each shared schedule is placed as a horizontally long rectangle with rounded corners and contains metadata as listed above. 
- [ ] Each shared schedule contains a button to open the document
Inspiration UI for the Shared with me page:
![Image](https://github.com/UMLCloudComputing/UniPath.io/assets/93165798/9f100375-c00a-402d-8449-6c603e7fc28c)
Here the items are in the shape of the button to open, and within the space there would metadata regarding the shared schedule
 
### Tasks:
- [ ] #49
- [ ] #50
- [ ] #51
- [ ] #52
- [ ] #53
- [ ] #54
- [ ] Others as the time comes? (Kind of hard to individually scope such a large story...)

Hints/Technologies:
- [ ] Account object integration with Schedule object
- [ ] "Shared with me" UI within account details
- [ ] Share account object data with AWS Cognito and AWS S3 Account object data
- [ ] Schedule object creation
