### ISSUE TITLE
As a user, I want to have an integrated Tasks management page so that I can manage my to-do lists for various categories

### ISSUE THREAD

**Issue by Gurpranked** [UMLCloudComputing/UniPath.io#78]
## User Story #: 8

**Description:**  
As a user, I want to have an integrated Tasks management page so that I can manage my to-do lists for various categories

### Acceptance Criteria:
- [ ] Be able to create a new tasks list
- [ ] Be able to mark a task as done
- [ ] Have DND functionality from one task list to another list
- [ ] Be able to mark a task as important and be focused to the top
- [ ] Have a default Important List with exclusively important tasks
- [ ] 

### Tasks:
- [ ] These can be made into their own issues and linked here using # and then the issue number. IE #45 for issue number 45 (*Add a button to enable dark mode*)

(*Optional*) Hints/Technologies:
- [ ] React JS
- [ ] Beautiful React DND
- [ ] Next JS
- [ ] AWS Amplify
